import { Member, PlanDetail, ChartData, DashboardStats, Trainer, Notification, GymEquipment, EquipmentIssue } from '@/types'

export const PLANS: PlanDetail[] = [
  {
    id: 'basic',
    name: 'Basic',
    price: { '1': 150000, '3': 420000, '6': 780000, '12': 1440000 },
    features: [
      'Akses gym jam 06.00 - 21.00',
      'Locker standard',
      'Akses cardio area',
      'Konsultasi fitness 1x/bulan',
      'Tidak termasuk kelas grup',
    ],
    color: '#6B7280',
  },
  {
    id: 'regular',
    name: 'Regular',
    price: { '1': 250000, '3': 690000, '6': 1260000, '12': 2280000 },
    features: [
      'Akses gym 24/7',
      'Locker premium',
      'Akses semua area',
      'Konsultasi fitness 2x/bulan',
      'Kelas grup (3x/minggu)',
      'Akses aplikasi tracking',
    ],
    popular: true,
    color: '#E94560',
  },
  {
    id: 'premium',
    name: 'Premium',
    price: { '1': 450000, '3': 1260000, '6': 2340000, '12': 4320000 },
    features: [
      'Akses gym 24/7 prioritas',
      'Locker VIP + shower private',
      'Akses semua area + VIP lounge',
      'Personal trainer 2x/minggu',
      'Kelas grup unlimited',
      'Nutrisi & meal plan konsultasi',
      'Guest pass 2x/bulan',
    ],
    color: '#0F3460',
  },
]

export const TRAINERS: Trainer[] = [
  {
    id: 't1',
    name: 'Andi Firmansyah',
    specialization: 'Strength & Muscle Building',
    experience: '8 tahun',
    avatar: 'AF',
    rating: 4.9,
    certifications: ['ACE Certified PT', 'NSCA-CPT', 'Nutrition Coach'],
    bio: 'Spesialis pembentukan otot dan kekuatan. Sudah melatih 200+ klien dengan hasil transformasi luar biasa.',
    availableSchedules: [
      { id: 's1', day: 'Senin & Rabu', time: '07:00 - 09:00', slots: 4, bookedSlots: 2 },
      { id: 's2', day: 'Selasa & Kamis', time: '17:00 - 19:00', slots: 4, bookedSlots: 1 },
      { id: 's3', day: 'Sabtu', time: '08:00 - 10:00', slots: 6, bookedSlots: 4 },
    ],
  },
  {
    id: 't2',
    name: 'Sari Dewi Kusuma',
    specialization: 'Cardio & Weight Loss',
    experience: '6 tahun',
    avatar: 'SD',
    rating: 4.8,
    certifications: ['ACSM CPT', 'Zumba Instructor', 'Yoga Alliance RYT 200'],
    bio: 'Ahli cardio dan penurunan berat badan. Metode latihan menyenangkan namun sangat efektif untuk membakar lemak.',
    availableSchedules: [
      { id: 's4', day: 'Senin, Rabu & Jumat', time: '06:00 - 07:30', slots: 5, bookedSlots: 3 },
      { id: 's5', day: 'Selasa & Kamis', time: '15:00 - 16:30', slots: 5, bookedSlots: 2 },
      { id: 's6', day: 'Minggu', time: '07:00 - 09:00', slots: 8, bookedSlots: 5 },
    ],
  },
  {
    id: 't3',
    name: 'Bima Arjuna Putra',
    specialization: 'Functional Training & HIIT',
    experience: '5 tahun',
    avatar: 'BA',
    rating: 4.7,
    certifications: ['ISSA CPT', 'CrossFit L2', 'TRX Certified'],
    bio: 'Pakar functional training dan HIIT. Membantu klien mencapai kebugaran optimal dengan latihan yang efisien dan dinamis.',
    availableSchedules: [
      { id: 's7', day: 'Senin & Jumat', time: '10:00 - 12:00', slots: 4, bookedSlots: 0 },
      { id: 's8', day: 'Rabu', time: '18:00 - 20:00', slots: 4, bookedSlots: 2 },
      { id: 's9', day: 'Sabtu & Minggu', time: '09:00 - 11:00', slots: 6, bookedSlots: 3 },
    ],
  },
  {
    id: 't4',
    name: 'Rini Wahyuni',
    specialization: 'Yoga, Pilates & Flexibility',
    experience: '7 tahun',
    avatar: 'RW',
    rating: 4.9,
    certifications: ['Yoga Alliance E-RYT 500', 'BASI Pilates', 'Meditation Coach'],
    bio: 'Instruktur yoga dan pilates bersertifikat internasional. Fokus pada keseimbangan tubuh, fleksibilitas, dan kesehatan mental.',
    availableSchedules: [
      { id: 's10', day: 'Selasa & Kamis', time: '08:00 - 09:30', slots: 8, bookedSlots: 6 },
      { id: 's11', day: 'Rabu & Jumat', time: '16:00 - 17:30', slots: 8, bookedSlots: 4 },
      { id: 's12', day: 'Minggu', time: '08:00 - 10:00', slots: 10, bookedSlots: 7 },
    ],
  },
]

export const GYM_EQUIPMENTS: GymEquipment[] = [
  {
    id: 'eq1',
    name: 'Treadmill',
    category: 'Kardio',
    icon: '🏃',
    description: 'Mesin lari otomatis yang memungkinkan Anda berlari atau berjalan di tempat dengan kecepatan dan kemiringan yang dapat disesuaikan.',
    benefits: ['Membakar kalori efektif', 'Meningkatkan kesehatan jantung', 'Melatih daya tahan tubuh', 'Bisa dikontrol intensitasnya'],
    muscleGroups: ['Paha depan', 'Betis', 'Hamstring', 'Gluteus'],
    difficulty: 'Pemula',
    tips: ['Mulai dengan kecepatan rendah 5-6 km/jam', 'Pegang handrail jika perlu keseimbangan', 'Pastikan postur tegak saat berlari', 'Cool down 5 menit sebelum berhenti'],
  },
  {
    id: 'eq2',
    name: 'Barbell',
    category: 'Beban Bebas',
    icon: '🏋️',
    description: 'Batang besi panjang yang bisa dipasangi beban di kedua ujungnya. Digunakan untuk latihan angkat beban seperti squat, deadlift, dan bench press.',
    benefits: ['Membangun massa otot', 'Meningkatkan kekuatan fungsional', 'Melatih banyak otot sekaligus', 'Progresif overload mudah dilakukan'],
    muscleGroups: ['Seluruh tubuh tergantung gerakan', 'Dada', 'Punggung', 'Paha'],
    difficulty: 'Menengah',
    tips: ['Selalu gunakan collar pengaman', 'Minta spotter saat angkat berat', 'Kuasai teknik dasar sebelum menambah beban', 'Jaga punggung tetap lurus'],
  },
  {
    id: 'eq3',
    name: 'Dumbbells',
    category: 'Beban Bebas',
    icon: '💪',
    description: 'Sepasang beban genggam yang digunakan untuk melatih otot tubuh bagian atas. Lebih fleksibel dari barbell karena bisa digunakan secara individual.',
    benefits: ['Melatih keseimbangan otot kanan-kiri', 'Range of motion lebih luas', 'Cocok untuk pemula', 'Banyak variasi gerakan'],
    muscleGroups: ['Bisep', 'Trisep', 'Bahu', 'Dada'],
    difficulty: 'Pemula',
    tips: ['Pilih beban yang tepat — bisa 8-12 repetisi dengan form benar', 'Kontrol gerakan naik dan turun', 'Jangan ayunkan tubuh saat angkat', 'Latih kedua sisi secara bergantian'],
  },
  {
    id: 'eq4',
    name: 'Lat Pulldown Machine',
    category: 'Mesin Beban',
    icon: '⬇️',
    description: 'Mesin untuk melatih otot latissimus dorsi (sayap belakang) dengan menarik bar dari atas ke bawah. Sangat baik untuk memperlebar otot punggung.',
    benefits: ['Membangun otot punggung atas', 'Alternatif pull-up untuk pemula', 'Mudah dikontrol bebannya', 'Meningkatkan postur tubuh'],
    muscleGroups: ['Latissimus dorsi', 'Bisep', 'Rhomboid', 'Trapezius bawah'],
    difficulty: 'Pemula',
    tips: ['Duduk tegak dan kunci posisi', 'Tarik bar ke dada bagian atas, bukan leher', 'Rasakan otot punggung bekerja', 'Kembali perlahan untuk maksimalkan otot'],
  },
  {
    id: 'eq5',
    name: 'Leg Press Machine',
    category: 'Mesin Beban',
    icon: '🦵',
    description: 'Mesin untuk melatih otot kaki dengan mendorong beban menggunakan kaki. Lebih aman dari squat untuk pemula karena punggung tertopang.',
    benefits: ['Melatih otot kaki dengan aman', 'Cocok untuk rehabilitasi', 'Mudah menambah beban besar', 'Meminimalkan risiko cedera punggung'],
    muscleGroups: ['Quadriceps', 'Hamstring', 'Gluteus', 'Betis'],
    difficulty: 'Pemula',
    tips: ['Posisikan kaki selebar bahu di platform', 'Jangan kunci lutut saat ekstensi penuh', 'Turunkan platform hingga lutut 90 derajat', 'Jaga punggung bawah menempel di sandaran'],
  },
  {
    id: 'eq6',
    name: 'Cable Machine',
    category: 'Mesin Beban',
    icon: '🔄',
    description: 'Mesin serbaguna menggunakan sistem kabel dan katrol yang bisa diatur ketinggiannya. Memungkinkan ratusan variasi gerakan untuk seluruh tubuh.',
    benefits: ['Sangat serbaguna', 'Resistance konstan sepanjang gerakan', 'Melatih stabilitas otot', 'Cocok untuk semua level'],
    muscleGroups: ['Fleksibel — hampir semua otot', 'Dada', 'Punggung', 'Bahu', 'Lengan'],
    difficulty: 'Menengah',
    tips: ['Atur ketinggian kabel sesuai gerakan', 'Stand jauh dari mesin untuk resistensi penuh', 'Kontrol gerakan, jangan biarkan beban jatuh', 'Eksplor berbagai attachment untuk variasi'],
  },
  {
    id: 'eq7',
    name: 'Rowing Machine',
    category: 'Kardio',
    icon: '🚣',
    description: 'Mesin kardio yang mensimulasikan gerakan mendayung. Melatih seluruh tubuh secara bersamaan dengan dampak rendah pada sendi.',
    benefits: ['Melatih 86% otot tubuh', 'Low impact pada sendi', 'Membakar kalori tinggi', 'Meningkatkan postur & koordinasi'],
    muscleGroups: ['Punggung', 'Kaki', 'Lengan', 'Core'],
    difficulty: 'Menengah',
    tips: ['Mulai dengan kaki mendorong, bukan lengan menarik', 'Jaga punggung tegak, jangan membungkuk', 'Rasio tarikan: 60% kaki, 20% core, 20% lengan', 'Mulai lambat dan konsisten'],
  },
  {
    id: 'eq8',
    name: 'Smith Machine',
    category: 'Mesin Beban',
    icon: '🏗️',
    description: 'Barbell yang terpasang pada rel vertikal dengan sistem pengunci otomatis. Lebih aman dari barbell bebas dan cocok untuk berlatih sendiri.',
    benefits: ['Lebih aman dari free barbell', 'Bisa latihan tanpa spotter', 'Gerakan lebih terkontrol', 'Bisa dikunci di posisi manapun'],
    muscleGroups: ['Dada', 'Bahu', 'Paha', 'Gluteus'],
    difficulty: 'Pemula',
    tips: ['Atur posisi bar sebelum mulai', 'Putar bar untuk mengunci/membuka', 'Posisi tubuh sedikit berbeda dari free barbell', 'Gunakan untuk squat, bench press, shoulder press'],
  },
  {
    id: 'eq9',
    name: 'Stationary Bike',
    category: 'Kardio',
    icon: '🚲',
    description: 'Sepeda statis untuk latihan kardio low-impact. Tersedia dalam dua jenis: upright bike (posisi tegak) dan recumbent bike (posisi bersandar).',
    benefits: ['Sangat ramah sendi', 'Cocok untuk semua usia', 'Meningkatkan kebugaran kardiovaskular', 'Bisa sambil membaca/menonton'],
    muscleGroups: ['Quadriceps', 'Hamstring', 'Betis', 'Gluteus'],
    difficulty: 'Pemula',
    tips: ['Sesuaikan ketinggian sadel agar lutut sedikit bengkok di bawah', 'Mulai dengan resistensi rendah', 'Target 20-45 menit untuk hasil optimal', 'Variasikan intensitas dengan interval training'],
  },
  {
    id: 'eq10',
    name: 'Pull-Up Bar',
    category: 'Beban Badan',
    icon: '⬆️',
    description: 'Palang horizontal untuk latihan pull-up dan chin-up. Salah satu latihan terbaik untuk membangun otot punggung dan lengan hanya dengan berat badan.',
    benefits: ['Tidak butuh beban tambahan', 'Membangun otot punggung & bisep', 'Melatih kekuatan grip', 'Bisa dilakukan di mana saja'],
    muscleGroups: ['Latissimus dorsi', 'Bisep', 'Rhomboid', 'Core'],
    difficulty: 'Lanjutan',
    tips: ['Pemula bisa mulai dengan resistance band sebagai bantuan', 'Genggam palang lebih lebar dari bahu', 'Tarik hingga dagu melewati bar', 'Turunkan badan perlahan untuk hasil maksimal'],
  },
  {
    id: 'eq11',
    name: 'Kettlebell',
    category: 'Beban Bebas',
    icon: '🔔',
    description: 'Beban berbentuk bola besi dengan pegangan di atas. Sangat efektif untuk latihan functional, cardio, dan kekuatan sekaligus.',
    benefits: ['Meningkatkan explosive power', 'Membakar kalori tinggi', 'Melatih koordinasi & keseimbangan', 'Serbaguna untuk banyak gerakan'],
    muscleGroups: ['Gluteus', 'Hamstring', 'Core', 'Bahu'],
    difficulty: 'Menengah',
    tips: ['Kuasai teknik swing sebelum gerakan kompleks', 'Berat ideal: 8-12kg untuk wanita, 16-24kg untuk pria pemula', 'Jaga punggung netral saat deadlift', 'Istirahat cukup antar set karena intensitas tinggi'],
  },
  {
    id: 'eq12',
    name: 'Foam Roller',
    category: 'Recovery',
    icon: '🟫',
    description: 'Silinder busa padat untuk self-myofascial release (pijat otot sendiri). Digunakan sebelum atau sesudah latihan untuk mengurangi ketegangan otot.',
    benefits: ['Mengurangi nyeri otot', 'Meningkatkan fleksibilitas', 'Mempercepat pemulihan', 'Mencegah cedera'],
    muscleGroups: ['IT band', 'Betis', 'Punggung atas', 'Quadriceps'],
    difficulty: 'Pemula',
    tips: ['Roll perlahan 30-60 detik per area', 'Berhenti di titik nyeri selama 20-30 detik', 'Hindari rolling langsung di tulang sendi', 'Gunakan setelah latihan untuk recovery'],
  },
]

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    type: 'promo',
    title: '🎉 Promo Bulan April!',
    message: 'Daftar paket 6 bulan atau 12 bulan dan dapatkan 1 bulan gratis + bonus sesi personal trainer. Berlaku hingga 30 April 2026.',
    date: '2026-04-01',
    read: false,
  },
  {
    id: 'n2',
    type: 'info',
    title: '🏗️ Renovasi Area Kolam Renang',
    message: 'Area kolam renang akan ditutup untuk renovasi pada 15-22 April 2026. Mohon maaf atas ketidaknyamanannya. Fasilitas lain tetap beroperasi normal.',
    date: '2026-04-10',
    read: false,
  },
  {
    id: 'n3',
    type: 'success',
    title: '✅ Kelas Baru: HIIT Express',
    message: 'Kami menghadirkan kelas HIIT Express 30 menit setiap Senin, Rabu, Jumat pukul 12:00-12:30. Cocok untuk Anda yang punya waktu terbatas di jam makan siang!',
    date: '2026-04-15',
    read: false,
  },
  {
    id: 'n4',
    type: 'warning',
    title: '⚠️ Jadwal Libur Nasional',
    message: 'Gym akan beroperasi dengan jam terbatas pada Hari Raya Idul Fitri (pukul 08:00-15:00). Pastikan Anda memeriksa jadwal sebelum berkunjung.',
    date: '2026-03-28',
    read: true,
  },
  {
    id: 'n5',
    type: 'info',
    title: '📱 Update Aplikasi Tersedia',
    message: 'Versi terbaru aplikasi Gym Cemerlang kini tersedia dengan fitur booking kelas online, tracking workout, dan notifikasi pengingat latihan.',
    date: '2026-03-20',
    read: true,
  },
]

export const MOCK_MEMBERS: Member[] = [
  {
    id: '1',
    name: 'Budi Santoso',
    email: 'budi@example.com',
    phone: '081234567890',
    birthDate: '1990-05-15',
    gender: 'male',
    address: 'Jl. Merdeka No. 12, Surabaya',
    plan: 'premium',
    duration: '12',
    status: 'active',
    registeredAt: '2024-01-15',
    startDate: '2024-01-15',
    endDate: '2025-01-15',
    referenceNumber: 'GYM-ABC123-XY1Z',
    trainerId: 't1',
    trainerSchedule: 's1',
    heightCm: 175,
    weightKg: 80,
  },
  {
    id: '2',
    name: 'Siti Rahayu',
    email: 'siti@example.com',
    phone: '082345678901',
    birthDate: '1995-08-22',
    gender: 'female',
    address: 'Jl. Pahlawan No. 5, Surabaya',
    plan: 'regular',
    duration: '6',
    status: 'active',
    registeredAt: '2024-02-10',
    startDate: '2024-02-10',
    endDate: '2024-08-10',
    referenceNumber: 'GYM-DEF456-AB2C',
    heightCm: 158,
    weightKg: 55,
  },
  {
    id: '3',
    name: 'Ahmad Fauzi',
    email: 'ahmad@example.com',
    phone: '083456789012',
    birthDate: '1988-12-03',
    gender: 'male',
    address: 'Jl. Diponegoro No. 8, Surabaya',
    plan: 'basic',
    duration: '1',
    status: 'expired',
    registeredAt: '2023-11-01',
    startDate: '2023-11-01',
    endDate: '2023-12-01',
    referenceNumber: 'GYM-GHI789-CD3E',
  },
  {
    id: '4',
    name: 'Dewi Kurniawati',
    email: 'dewi@example.com',
    phone: '084567890123',
    birthDate: '1998-03-18',
    gender: 'female',
    address: 'Jl. Sudirman No. 25, Surabaya',
    plan: 'regular',
    duration: '3',
    status: 'pending',
    registeredAt: '2024-03-01',
    startDate: '2024-03-01',
    endDate: '2024-06-01',
    referenceNumber: 'GYM-JKL012-EF4G',
  },
  {
    id: '5',
    name: 'Rizky Pratama',
    email: 'rizky@example.com',
    phone: '085678901234',
    birthDate: '1992-07-29',
    gender: 'male',
    address: 'Jl. Ahmad Yani No. 15, Surabaya',
    plan: 'premium',
    duration: '6',
    status: 'active',
    registeredAt: '2024-02-20',
    startDate: '2024-02-20',
    endDate: '2024-08-20',
    referenceNumber: 'GYM-MNO345-GH5I',
    trainerId: 't3',
    trainerSchedule: 's7',
    heightCm: 170,
    weightKg: 90,
  },
  {
    id: '6',
    name: 'Maya Indah',
    email: 'maya@example.com',
    phone: '086789012345',
    birthDate: '1993-11-14',
    gender: 'female',
    address: 'Jl. Gatot Subroto No. 7, Surabaya',
    plan: 'basic',
    duration: '3',
    status: 'active',
    registeredAt: '2024-03-05',
    startDate: '2024-03-05',
    endDate: '2024-06-05',
    referenceNumber: 'GYM-PQR678-IJ6K',
    heightCm: 162,
    weightKg: 48,
  },
]

export const CHART_DATA: ChartData[] = [
  { month: 'Sep', registrations: 28, revenue: 8500000 },
  { month: 'Okt', registrations: 35, revenue: 11200000 },
  { month: 'Nov', registrations: 42, revenue: 14800000 },
  { month: 'Des', registrations: 38, revenue: 12300000 },
  { month: 'Jan', registrations: 55, revenue: 18600000 },
  { month: 'Feb', registrations: 63, revenue: 22400000 },
]

export const DASHBOARD_STATS: DashboardStats = {
  totalMembers: 524,
  thisMonthRegistrations: 63,
  activeMembers: 418,
  monthlyRevenue: 22400000,
}

export const PLAN_DISTRIBUTION = [
  { name: 'Basic', value: 35, color: '#6B7280' },
  { name: 'Regular', value: 45, color: '#E94560' },
  { name: 'Premium', value: 20, color: '#0F3460' },
]

export const EQUIPMENT_ISSUES: EquipmentIssue[] = [
  {
    id: 'ei1',
    name: 'Treadmill',
    category: 'Kardio',
    icon: '🏃',
    totalIssues: 18,
    lastMaintenance: '2026-04-01',
    status: 'kritis',
    issues: [
      { month: 'Sep', count: 2, description: 'Belt slip, motor overheat' },
      { month: 'Okt', count: 3, description: 'Display mati, belt aus' },
      { month: 'Nov', count: 4, description: 'Motor berisik, incline error' },
      { month: 'Des', count: 2, description: 'Belt slip, sensor kecepatan rusak' },
      { month: 'Jan', count: 4, description: 'Motor overheat, display error' },
      { month: 'Feb', count: 3, description: 'Belt aus, papan bawah retak' },
    ],
    maintenanceTips: [
      'Lumasi belt setiap 3 bulan sekali',
      'Bersihkan motor dari debu setiap bulan',
      'Periksa tegangan belt secara rutin',
      'Ganti belt setiap 1-2 tahun tergantung pemakaian',
    ],
  },
  {
    id: 'ei2',
    name: 'Cable Machine',
    category: 'Mesin Beban',
    icon: '🔄',
    totalIssues: 12,
    lastMaintenance: '2026-03-15',
    status: 'perlu-perhatian',
    issues: [
      { month: 'Sep', count: 1, description: 'Kabel fraying' },
      { month: 'Okt', count: 2, description: 'Pulley macet, kabel putus' },
      { month: 'Nov', count: 2, description: 'Pin selector rusak' },
      { month: 'Des', count: 1, description: 'Kabel fraying' },
      { month: 'Jan', count: 3, description: 'Pulley aus, kabel putus, pin selector' },
      { month: 'Feb', count: 3, description: 'Kabel putus, pulley macet' },
    ],
    maintenanceTips: [
      'Periksa kondisi kabel setiap minggu',
      'Lumasi pulley setiap 2 bulan',
      'Ganti kabel setiap 12-18 bulan',
      'Cek pin selector setiap bulan',
    ],
  },
  {
    id: 'ei3',
    name: 'Rowing Machine',
    category: 'Kardio',
    icon: '🚣',
    totalIssues: 9,
    lastMaintenance: '2026-03-20',
    status: 'perlu-perhatian',
    issues: [
      { month: 'Sep', count: 1, description: 'Seat roller aus' },
      { month: 'Okt', count: 1, description: 'Chain berisik' },
      { month: 'Nov', count: 2, description: 'Display error, damper macet' },
      { month: 'Des', count: 1, description: 'Seat roller aus' },
      { month: 'Jan', count: 2, description: 'Chain aus, handle grip copot' },
      { month: 'Feb', count: 2, description: 'Damper macet, display mati' },
    ],
    maintenanceTips: [
      'Lumasi chain setiap bulan dengan chain oil',
      'Periksa seat roller setiap 2 bulan',
      'Bersihkan monorail seat setiap minggu',
      'Kalibrasi monitor setiap 6 bulan',
    ],
  },
  {
    id: 'ei4',
    name: 'Leg Press Machine',
    category: 'Mesin Beban',
    icon: '🦵',
    totalIssues: 7,
    lastMaintenance: '2026-04-10',
    status: 'baik',
    issues: [
      { month: 'Sep', count: 0, description: '-' },
      { month: 'Okt', count: 1, description: 'Pin macet' },
      { month: 'Nov', count: 1, description: 'Rel berderit' },
      { month: 'Des', count: 2, description: 'Pin macet, bantalan aus' },
      { month: 'Jan', count: 2, description: 'Rel berderit, pin rusak' },
      { month: 'Feb', count: 1, description: 'Bantalan platform retak' },
    ],
    maintenanceTips: [
      'Lumasi rel peluncur setiap 3 bulan',
      'Periksa pin selector setiap bulan',
      'Cek kondisi bantalan kaki setiap 3 bulan',
      'Kencangkan baut-baut setiap 6 bulan',
    ],
  },
  {
    id: 'ei5',
    name: 'Stationary Bike',
    category: 'Kardio',
    icon: '🚲',
    totalIssues: 6,
    lastMaintenance: '2026-04-05',
    status: 'baik',
    issues: [
      { month: 'Sep', count: 1, description: 'Pedal copot' },
      { month: 'Okt', count: 0, description: '-' },
      { month: 'Nov', count: 1, description: 'Resistance knob rusak' },
      { month: 'Des', count: 1, description: 'Display error' },
      { month: 'Jan', count: 2, description: 'Sadel longgar, pedal berisik' },
      { month: 'Feb', count: 1, description: 'Resistance knob rusak' },
    ],
    maintenanceTips: [
      'Periksa kencangan sadel dan stang setiap bulan',
      'Lumasi bearing pedal setiap 3 bulan',
      'Bersihkan dan kalibrasi resistance setiap 6 bulan',
      'Periksa display dan sensor rpm setiap bulan',
    ],
  },
]

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Budi Santoso',
    role: 'Member Premium',
    avatar: 'BS',
    rating: 5,
    text: 'Pendaftaran online sangat mudah! Dalam 5 menit sudah selesai dan langsung bisa akses gym. Fasilitasnya top banget!',
  },
  {
    id: 2,
    name: 'Siti Rahayu',
    role: 'Member Regular',
    avatar: 'SR',
    rating: 5,
    text: 'Sistem baru ini memudahkan banget. Tidak perlu antri panjang, daftar dari rumah, langsung aktif keanggotaan. Instrukturnya juga profesional.',
  },
  {
    id: 3,
    name: 'Rizky Pratama',
    role: 'Member Premium',
    avatar: 'RP',
    rating: 5,
    text: 'Sudah 6 bulan jadi member, perkembangan fisik saya signifikan. Workout tracker di sistem sangat membantu monitoring progress.',
  },
  {
    id: 4,
    name: 'Maya Indah',
    role: 'Member Basic',
    avatar: 'MI',
    rating: 4,
    text: 'Harga terjangkau dengan kualitas fasilitas yang sangat baik. Pendaftaran online bisa dilakukan kapan saja, sangat fleksibel.',
  },
]

export const PROGRAMS = [
  {
    id: 1,
    name: 'Fitness Dasar',
    description: 'Program ideal untuk pemula yang ingin memulai perjalanan fitness dengan panduan lengkap dari instruktur berpengalaman.',
    duration: '60 menit',
    level: 'Pemula',
    gradient: 'from-blue-600 to-blue-800',
    icon: '💪',
  },
  {
    id: 2,
    name: 'Cardio Intensif',
    description: 'Bakar kalori maksimal dengan program cardio intensitas tinggi yang dirancang untuk meningkatkan stamina dan daya tahan.',
    duration: '45 menit',
    level: 'Menengah',
    gradient: 'from-red-600 to-red-800',
    icon: '🏃',
  },
  {
    id: 3,
    name: 'Strength Training',
    description: 'Bangun massa otot dan kekuatan dengan program latihan beban terstruktur dan progresif bersama personal trainer.',
    duration: '75 menit',
    level: 'Lanjutan',
    gradient: 'from-gray-700 to-gray-900',
    icon: '🏋️',
  },
  {
    id: 4,
    name: 'Yoga & Pilates',
    description: 'Perkuat fleksibilitas, keseimbangan, dan ketenangan jiwa dengan sesi yoga dan pilates yang dipandu instruktur bersertifikat.',
    duration: '60 menit',
    level: 'Semua Level',
    gradient: 'from-purple-600 to-purple-800',
    icon: '🧘',
  },
]
